<?php


function register_brand_custom_post_type()
{
    register_post_type('brand', array(
        'label' => 'Brands',
        'labels' => array(
            'name' => 'Brands',
            'singular_name' => 'Brand',
            'menu_name' => 'Brands',
            'all_items' => 'All Brands',
            'add_new' => 'Add new',
            'add_new_item' => 'Add new Brand',
            'edit_item' => 'Edit Brand',
            'new_item' => 'New Brand',
            'view_item' => 'View Brand',
            'view_items' => 'View Brands',
            'search_items' => 'Search Brands',
            'not_found' => 'No Brands found',
            'not_found_in_trash' => 'No Brands found in trash',
            'parent' => 'Parent Brand:',
            'featured_image' => 'Featured image for this Brand',
            'set_featured_image' => 'Set featured image for this Brand',
            'remove_featured_image' => 'Remove featured image for this Brand',
            'use_featured_image' => 'Use as featured image for this Brand',
            'archives' => 'Brand archives',
            'insert_into_item' => 'Insert into Brand',
            'uploaded_to_this_item' => 'Upload to this Brand',
            'filter_items_list' => 'Filter Brands list',
            'items_list_navigation' => 'Brands list navigation',
            'items_list' => 'Brands list',
            'attributes' => 'Brands attributes',
            'name_admin_bar' => 'Brand',
            'item_published' => 'Brand published',
            'item_published_privately' => 'Brand published privately.',
            'item_reverted_to_draft' => 'Brand reverted to draft.',
            'item_scheduled' => 'Brand scheduled',
            'item_updated' => 'Brand updated.',
            'parent_item_colon' => 'Parent Brand:',
        ),
        'description' => 'Product Brands',
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'show_in_rest' => true,
        'rest_base' => 'brands',
        'rest_controller_class' => 'WP_REST_Posts_Controller',
        'has_archive' => false,
        'show_in_menu' => true,
        'show_in_nav_menus' => false,
        'delete_with_user' => false,
        'exclude_from_search' => true,
        'capability_type' => 'post',
        'map_meta_cap' => true,
        'hierarchical' => false,
        'rewrite' => ['slug' => 'brands', 'with_front' => true],
        'query_var' => true,
        'menu_icon' => 'dashicons-hammer',
        'supports' => ['title', 'thumbnail'],
    ));
}


function register_faq_custom_post_type()
{
    register_post_type('faq', array(
        'label' => 'FAQs',
        'labels' => array(
            'name' => 'FAQs',
            'singular_name' => 'FAQ',
            'menu_name' => 'FAQs',
            'all_items' => 'All FAQs',
            'add_new' => 'Add new',
            'add_new_item' => 'Add new FAQ',
            'edit_item' => 'Edit FAQ',
            'new_item' => 'New FAQ',
            'view_item' => 'View FAQ',
            'view_items' => 'View FAQs',
            'search_items' => 'Search FAQs',
            'not_found' => 'No FAQs found',
            'not_found_in_trash' => 'No FAQs found in trash',
            'parent' => 'Parent FAQ:',
            'featured_image' => 'Featured image for this FAQ',
            'set_featured_image' => 'Set featured image for this FAQ',
            'remove_featured_image' => 'Remove featured image for this FAQ',
            'use_featured_image' => 'Use as featured image for this FAQ',
            'archives' => 'FAQ archives',
            'insert_into_item' => 'Insert into FAQ',
            'uploaded_to_this_item' => 'Upload to this FAQ',
            'filter_items_list' => 'Filter FAQs list',
            'items_list_navigation' => 'FAQs list navigation',
            'items_list' => 'FAQs list',
            'attributes' => 'FAQs attributes',
            'name_admin_bar' => 'FAQ',
            'item_published' => 'FAQ published',
            'item_published_privately' => 'FAQ published privately.',
            'item_reverted_to_draft' => 'FAQ reverted to draft.',
            'item_scheduled' => 'FAQ scheduled',
            'item_updated' => 'FAQ updated.',
            'parent_item_colon' => 'Parent FAQ:',
        ),
        'description' => 'Product FAQs',
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'show_in_rest' => true,
        'rest_base' => 'faqs',
        'rest_controller_class' => 'WP_REST_Posts_Controller',
        'has_archive' => false,
        'show_in_menu' => true,
        'show_in_nav_menus' => false,
        'delete_with_user' => false,
        'exclude_from_search' => true,
        'capability_type' => 'post',
        'map_meta_cap' => true,
        'hierarchical' => false,
        'rewrite' => ['slug' => 'faqs', 'with_front' => true],
        'query_var' => true,
        'menu_icon' => 'dashicons-editor-help',
        'supports' => ['title', 'editor'],
    ));
}


function register_brand_ambassador_custom_post_type()
{
    register_post_type('brand-ambassador', array(
        'label' => 'Brand Ambassadors',
        'labels' => array(
            'name' => 'Brand Ambassadors',
            'singular_name' => 'Brand Ambassador',
            'menu_name' => 'Brand Ambassadors',
            'all_items' => 'All Brand Ambassadors',
            'add_new' => 'Add new',
            'add_new_item' => 'Add new Brand Ambassador',
            'edit_item' => 'Edit Brand Ambassador',
            'new_item' => 'New Brand Ambassador',
            'view_item' => 'View Brand Ambassador',
            'view_items' => 'View Brand Ambassadors',
            'search_items' => 'Search Brand Ambassadors',
            'not_found' => 'No Brand Ambassadors found',
            'not_found_in_trash' => 'No Brand Ambassadors found in trash',
            'parent' => 'Parent Brand Ambassador:',
            'featured_image' => 'Featured image for this Brand Ambassador',
            'set_featured_image' => 'Set featured image for this Brand Ambassador',
            'remove_featured_image' => 'Remove featured image for this Brand Ambassador',
            'use_featured_image' => 'Use as featured image for this Brand Ambassador',
            'archives' => 'Brand Ambassador archives',
            'insert_into_item' => 'Insert into Brand Ambassador',
            'uploaded_to_this_item' => 'Upload to this Brand Ambassador',
            'filter_items_list' => 'Filter Brand Ambassadors list',
            'items_list_navigation' => 'Brand Ambassadors list navigation',
            'items_list' => 'Brand Ambassadors list',
            'attributes' => 'Brand Ambassadors attributes',
            'name_admin_bar' => 'Brand Ambassador',
            'item_published' => 'Brand Ambassador published',
            'item_published_privately' => 'Brand Ambassador published privately.',
            'item_reverted_to_draft' => 'Brand Ambassador reverted to draft.',
            'item_scheduled' => 'Brand Ambassador scheduled',
            'item_updated' => 'Brand Ambassador updated.',
            'parent_item_colon' => 'Parent Brand Ambassador:',
        ),
        'description' => 'Product Brand Ambassadors',
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'show_in_rest' => true,
        'rest_base' => 'brand-ambassadors',
        'rest_controller_class' => 'WP_REST_Posts_Controller',
        'has_archive' => false,
        'show_in_menu' => true,
        'show_in_nav_menus' => false,
        'delete_with_user' => false,
        'exclude_from_search' => true,
        'capability_type' => 'post',
        'map_meta_cap' => true,
        'hierarchical' => false,
        'rewrite' => ['slug' => 'brand-ambassadors', 'with_front' => true],
        'query_var' => true,
        'menu_icon' => 'dashicons-groups',
        'supports' => ['title'],
    ));
}


function register_wheel_package_markup_custom_post_type()
{
    register_post_type('wheel-package-markup', array(
        'label' => 'Wheel Package Markups',
        'labels' => array(
            'name' => 'Wheel Package Markups',
            'singular_name' => 'Wheel Package Markup',
            'menu_name' => 'Wheel Package Markups',
            'all_items' => 'All Wheel Package Markups',
            'add_new' => 'Add new',
            'add_new_item' => 'Add new Wheel Package Markup',
            'edit_item' => 'Edit Wheel Package Markup',
            'new_item' => 'New Wheel Package Markup',
            'view_item' => 'View Wheel Package Markup',
            'view_items' => 'View Wheel Package Markups',
            'search_items' => 'Search Wheel Package Markups',
            'not_found' => 'No Wheel Package Markups found',
            'not_found_in_trash' => 'No Wheel Package Markups found in trash',
            'parent' => 'Parent Wheel Package Markup:',
            'featured_image' => 'Featured image for this Wheel Package Markup',
            'set_featured_image' => 'Set featured image for this Wheel Package Markup',
            'remove_featured_image' => 'Remove featured image for this Wheel Package Markup',
            'use_featured_image' => 'Use as featured image for this Wheel Package Markup',
            'archives' => 'Wheel Package Markup archives',
            'insert_into_item' => 'Insert into Wheel Package Markup',
            'uploaded_to_this_item' => 'Upload to this Wheel Package Markup',
            'filter_items_list' => 'Filter Wheel Package Markups list',
            'items_list_navigation' => 'Wheel Package Markups list navigation',
            'items_list' => 'Wheel Package Markups list',
            'attributes' => 'Wheel Package Markups attributes',
            'name_admin_bar' => 'Wheel Package Markup',
            'item_published' => 'Wheel Package Markup published',
            'item_published_privately' => 'Wheel Package Markup published privately.',
            'item_reverted_to_draft' => 'Wheel Package Markup reverted to draft.',
            'item_scheduled' => 'Wheel Package Markup scheduled',
            'item_updated' => 'Wheel Package Markup updated.',
            'parent_item_colon' => 'Parent Wheel Package Markup:',
        ),
        'description' => 'Product Wheel Package Markups',
        'public' => true,
        'publicly_queryable' => true,
        'show_ui' => true,
        'show_in_rest' => true,
        'rest_base' => 'wheel-package-markups',
        'rest_controller_class' => 'WP_REST_Posts_Controller',
        'has_archive' => false,
        'show_in_menu' => true,
        'show_in_nav_menus' => false,
        'delete_with_user' => false,
        'exclude_from_search' => true,
        'capability_type' => 'post',
        'map_meta_cap' => true,
        'hierarchical' => false,
        'rewrite' => ['slug' => 'wheel-package-markups', 'with_front' => true],
        'query_var' => true,
        'menu_icon' => 'dashicons-car',
        'supports' => ['title'],
    ));
}


function register_custom_post_types()
{
    register_brand_custom_post_type();
    register_faq_custom_post_type();
    register_brand_ambassador_custom_post_type();
    register_wheel_package_markup_custom_post_type();
}

add_action('init', 'register_custom_post_types');
